function Cube(name, rarity, flavortext, price, image, box) {
	this.name = name
	this.rarity = rarity
	this.flavortext = flavortext
	this.price = price
	this.image = image
	this.box = box
	this.cubeid = cubeid
	cubeid++
	allcubes.push(this)
	trueallcubes.push(this)
}
/*function Immutablecube(name, rarity, flavortext, price, image) {
	this.name = name
	this.rarity = rarity
	this.flavortext = flavortext
	this.price = price
	this.image = image
}*/
function Immutablecube(cube) { // function to use when adding cubes to player's inventory, prevents mutation of the original cube
	this.name = cube.name
	this.rarity = cube.rarity
	this.flavortext = cube.flavortext
	this.price = cube.price
	this.image = cube.image
	this.cubeid = cube.cubeid
	this.immutableid = immutableid
	immutableid++
}
immutableid = 0
trueallcubes = []
allcubes =[]
cubeid = 0;
//CUBE SERIES #1, 16 cubes
const bluecube = new Cube("Blue Cube", light_green, "It's like a 3cm x 3cm x 3cm lego with no connecting parts!", 25, "sprites/bluecube.png")
const redcube = new Cube("Red Cube", light_green, "It's like a 3cm x 3cm x 3cm lego with no connecting parts!", 20, "sprites/redcube.png")
const greencube = new Cube("Green Cube", light_green, "It's like a 3cm x 3cm x 3cm lego with no connecting parts!", 75, "sprites/greencube.png")
const purplecube = new Cube("Purple Cube", light_green, "It's like a 3cm x 3cm x 3cm lego with no connecting parts!", 50, "sprites/purplecube.png")
const greenmushroomcube = new Cube("Green Mushroom Cube", green, "Psychadelic Square!", 120, "sprites/greenmushroomcube.png")
const bluemushroomcube = new Cube("Blue Mushroom Cube", green, "It's a mushroom but like a block.. odd", 310, "sprites/bluemushroomcube.png")
const ironcube = new Cube("Iron Cube", blue, "Solid iron cube, kinda heavy tbh.", 1212, "sprites/ironcube.png")
const redmushroomcube = new Cube("Red  Mushroom Cube", blue, "There we go, the classic 'shroom.", 1534, "sprites/redmushroomcube.png")
const hologramcube = new Cube("Holo-Cube", purple, "This is a pretty cool looking cube... too bad it's only a refraction of light, and therefore, intangible.", 2050, "sprites/hologramcube.png")
const coppercube = new Cube("Copper Cube", purple, "This seems impractical for copper's main use.", 1570, "sprites/coppercube.png")
const goldcube = new Cube("Gold Cube", orange, "Super heavy, and expensive!", 4120, "sprites/goldcube.png")
const icecube = new Cube("Ice Cube", orange, "Not to be confused with the artist.", 3020, "sprites/icecube.png")
const diamondcube = new Cube("Diamond Cube", red, "A small cube of diamonds, nice if you like diamonds", 13920, "sprites/diamondcube.png")
const emeraldcube = new Cube("Emerald Cube", red, "It's like green diamonds.", 16816, "sprites/emeraldcube.png")
const plastiquecube = new Cube("Plastique Cube", black, "This stylized cube is decorated with a circuitboard pattern.", 74048, "sprites/plastiquecube.png")
const aspectscube = new Cube("Aspect's Cube", black, "Smells like more cubes...", 122912, "sprites/aspectscube.png")
// CUBE SERIES #2, 19 cubes
const bluetargetcube = new Cube("Blue Target Cube", light_green, "A small cube built as a replica of a bullseye", 30, "sprites/bluetargetcube.png")
const browntargetcube = new Cube("Brown Target Cube", light_green, "A small cube built as a replica of a bullseye", 12, "sprites/browntargetcube.png")
const greentargetcube = new Cube("Green Target Cube", light_green, "A small cube built as a replica of a bullseye", 56, "sprites/greentargetcube.png")
const pinktargetcube = new Cube("Pink Target Cube", green, "A small cube built as a replica of a bullseye", 90, "sprites/pinktargetcube.png")
const purpletargetcube = new Cube("Purple Target Cube", green, "A small cube built as a replica of a bullseye", 156, "sprites/purpletargetcube.png")
const redtargetcube = new Cube("Red Target Cube", green, "A small cube built as a replica of a bullseye", 156, "sprites/redtargetcube.png")
const bluegalaxycube = new Cube("Blue Galaxy Cube", blue, "A small cube painted with a hydrographic of a galaxy.", 1612, "sprites/bluegalaxycube.png")
const pinkgalaxycube = new Cube("Pink Galaxy Cube", blue, "A small cube painted with a hydrographic of a galaxy.", 1539, "sprites/pinkgalaxycube.png")
const purplegalaxycube = new Cube("Purple Galaxy Cube", blue, "A small cube painted with a hydrographic of a galaxy.", 1798, "sprites/purplegalaxycube.png")
const redgalaxycube = new Cube("Red Galaxy Cube", blue, "A small cube painted with a hydrographic of a galaxy.", 1282, "sprites/redgalaxycube.png")
const galaxycube = new Cube("Gold Galaxy Cube", purple, "A small cube painted with a golden hydrographic of a galaxy.", 2679, "sprites/yellowgalaxycube.png")
const mosaicocube = new Cube("Mosaico", purple, "A stunning amount of detail applied to a small 3x3x3 cube.", 2358, "sprites/mosaicocube.png")
const mosaicacube = new Cube("Mosaica", purple, "The patterns and divets of this cube are soothing to hold in your hand.", 2778, "sprites/mosaicacube.png")
const boomcube = new Cube("BOOM! Cube", orange, "A small, heavy cube painted with B-O-O-M on all sides. It smells of gunpowder.", 3763, "sprites/boomcube.png")
const teleportationcube = new Cube("Teleportation Cube", orange, "A small cube that reminds you of... cake..?", 5719, "sprites/teleportationcube.png")
const pillarcube = new Cube("Pillar Cube", orange, "Despite comprising of only solid marble, it emits a catchy tune.", 5379, "sprites/pillarcube.png")
const dice = new Cube("The D6", red, "A normal sized 6-sided die made from ivory and indian ink.", 13951, "sprites/dice.png")
const neoncube = new Cube("Neon Cube", red, "This cube is one small multicolored neon light, complete with an on-off switch.", 14398, "sprites/neoncube.png")
const binarycube = new Cube("Binary Cube", black, "The cube shifts little by little every moment...", 57937, "sprites/binarycube.png")
// CUBE SERIES #3, 17 cubes
const arascube = new Cube("Interdimensional Cube", black, "A tear in the fabric of space, you can feel it pulsing with cosmic energy <br/> By Arachnix", 138612, "sprites/arascube.png")
const bluecheckeredcube = new Cube("Blue Checkered Cube", light_green, "A painted, checkered cube", 70, "sprites/bluecheckeredcube.png")
const checkeredcube = new Cube("Checkered Cube", light_green, "A painted, checkered cube", 100, "sprites/checkeredcube.png")
const cleanerscube = new Cube("The Cleaner's Cube", red, "A cube dedicated to those who would stop at nothing in their quest for rare items. <br/> By Kenny", 14682, "sprites/cleanerscube.png")
const cyangrass = new Cube("Cyan Grass", green, "A cube of dirt with colored grass growing atop it.", 127, "sprites/cyangrass.png")
const dirtbutwithoutcopyrightcube = new Cube("Weird Dirt Cube", blue, "This is like a gross ass piece of dirt..? Wait is this even dirt? <br/> By Trevis", 1998, "sprites/dirtbutwithoutcopyrightcube.png")
const holycube = new Cube("Holy Cube", purple, "A light, thin cube that looks like a communion wafer.", 1630, "sprites/holycube.png")
const holeycube = new Cube("Holey Cube", purple, "a tiny cube of swiss that doesn't smell for some reason", 1992, "sprites/holeycube.png")
const minecraftgrass = new Cube("Grass Cube", blue, "A cube of dirt with colored grass growing atop it.", 1660, "sprites/minecraftgrass.png")
const mutescube = new Cube("M.U.T.E.", black, "When you gaze into the cube, you feel an emptiness that leaves you sad. <br/> By Mute", 123023, "sprites/mutescube.png")
const pinkcheckeredcube = new Cube("Pink Checkered Cube", light_green, "A painted, checkered cube", 67, "sprites/pinkcheckeredcube.png")
const purplegrass = new Cube("Purple Grass", green, "A cube of dirt with colored grass growing atop it.", 1593, "sprites/purplegrass.png")
const redgrass = new Cube("Red Grass", blue, "A cube of dirt with colored grass growing atop it.", 220, "sprites/redgrass.png")
const invisiblecube = new Cube("Invisible Cube", orange, "uhh.. is this sold air?", 3569, "sprites/invisiblecube.png")
const mintycube = new Cube("Minty Cube", orange, "This small cube emits a nice, minty smell.", 6123, "sprites/mintycube.png")
const redeye = new Cube("Red Eye", light_green, "A cube painted to look like an eye. eew.", 175, "sprites/redeye.png")
const yelloweye = new Cube("Yellow Eye", light_green, "A cube painted to look like an eye. eew.", 104, "sprites/yelloweye.png")
// CUBE SERIES #4, 20 cubes
const bluepillcube = new Cube("Blue Pill Cube", light_green, "a thinner cube that looks like a pill! (dont swallow it; it's not actually medicine)", 23, "sprites/cubeseries4/bluepillcube.png")
const pinkpillcube = new Cube("Pink Pill Cube", light_green, "a thinner cube that looks like a pill! (dont swallow it; it's not actually medicine)", 44, "sprites/cubeseries4/pinkpillcube.png")
const bluestripedcube = new Cube("Blue Striped Cube", light_green, "a small cube painted to have little stripes", 76, "sprites/cubeseries4/bluestripedcube.png")
const greenstripedcube = new Cube("Green Striped Cube", light_green, "a small cube painted to have little stripes", 63, "sprites/cubeseries4/greenstripedcube.png")
const purplestripedcube = new Cube("Purple Striped Cube", light_green, "a small cube painted to have little stripes", 38, "sprites/cubeseries4/purplestripedcube.png")
const greenpillcube = new Cube("Green Pill Cube", green, "a thinner cube that looks like a pill! (dont swallow it; it's not actually medicine)", 177, "sprites/cubeseries4/greenpillcube.png")
const brownstripedcube = new Cube("Brown Striped Cube", green, "a small cube painted to have little stripes", 151, "sprites/cubeseries4/brownstripedcube.png")
const burgercube = new Cube("Burger Cube", green, "the burger. a staple of the american diet, this thing is almost the perfect quick meal!", 341, "sprites/cubeseries4/burgercube.png")
const cheeseburgercube = new Cube("Cheeseburger Cube", green, "the superior burger.", 557, "sprites/cubeseries4/cheeseburgercube.png")
const stripedcube = new Cube("Striped Cube", blue, "a small cube painted to have little stripes, this is the most desirable version because it is the standard type.", 1176, "sprites/cubeseries4/stripedcube.png")
const bulletcube = new Cube("Bullet Cube", blue, "this small cube has been colored as a bullet!, even smells like one too..", 1201, "sprites/cubeseries4/bulletcube.png")
const rustycube = new Cube("Rusty Cube", blue, "this cube is... uhh.. rusty. that's it's only notable feature.", 1347, "sprites/cubeseries4/rustycube.png")
const lemonke = new Cube("Le Monke", purple, "le monke is yes <br/> by lolzMonkey", 2699, "sprites/cubeseries4/lemonkecube.png")
const yellowpillcube = new Cube("Pink Pill Cube", light_green, "a thinner cube that looks like a pill! (dont swallow it; it's not actually medicine)", 44, "sprites/cubeseries4/pinkpillcube.png")
const shotgunshellcube = new Cube("Shotgun Shell Cube", purple, "a small cube that has been modeled like a standard shotgun shell.", 2319, "sprites/cubeseries4/shotgunshellcube.png")
const buddycube = new Cube("Buddy Cube", orange, "this little cube says 'buddy' in fine print on the bottom, colored to look like a half-dead face or something. freaky.", 4461, "sprites/cubeseries4/buddycube.png")
const dlorecube = new Cube("Cube of Lore", red, "this cube reminds you of a very overpriced sniper rifle in some other game...<br/> by OK BOOMER (sorta)", 23012, "sprites/cubeseries4/dlorecube.png")
const nebulacube = new Cube("Nebula Cube", red, "a glass cube with colored glass inside giving the optical illusion that it is a nebula; it is very nice", 19289, "sprites/nebulacube.png")
const eventhorizoncube = new Cube("Event Horizon", black, "you can feel its inescapable force pulling you in.<br/> by Arachnix", 170432, "sprites/cubeseries4/eventhorizon.png")
const loadingcube = new Cube("Loading Cube", black, "just wait... it'll finish eventually.", 156809, "sprites/cubeseries4/loadingcube.gif")
// Superstitious box
const thefoolcube = new Cube("I - The Fool", light_green, "The back of this cube has been stylized with a picture of a jester", 50, "sprites/superstitiousbox/1tarot.png")
const themagiciancube = new Cube("II - The Magician", light_green, "The back of this cube has been stylized with an artists rendition of a magician (the actually magical kind)", 29, "sprites/superstitiousbox/2tarot.png")
const thehighpriestesscube = new Cube("III - The High Priestess", light_green, "The back of this cube has been stylized with a drawing of a priestess", 180, "sprites/superstitiousbox/3tarot.png")
const theemperorcube = new Cube("IV - The Emperor", light_green, "The back of this cube has been stylized with an emperor", 156, "sprites/superstitiousbox/4tarot.png")
const theheirophantcube = new Cube("V - The Heirophant", green, "The back of this cube has been stylized with a bishop giving to the poor and misguided", 369, "sprites/superstitiousbox/5tarot.png")
const theloverscube = new Cube("VI - The Lovers", green, "The back of this cube has been stylized with a man and a woman", 596, "sprites/superstitiousbox/6tarot.png")
const thechariotcube = new Cube("VII - The Chariot", green, "The back of this cube has been stylized with an actual chariot", 198, "sprites/superstitiousbox/7tarot.png")
const justicecube = new Cube("VIII - Justice", green, "The back of this cube has been stylized with Raguel, the angel of justice.", 791, "sprites/superstitiousbox/8tarot.png")
const hermitcube = new Cube("IX - The Hermit", blue, "The back of this cube has been stylized with an old miser", 861, "sprites/superstitiousbox/9tarot.png")
const wheeloffortunecube = new Cube("X - Wheel Of Fortune", blue, "The back of this cube has been stylized with two men observing a wheel spin", 1286, "sprites/superstitiousbox/10tarot.png")
const strengthcube = new Cube("XI - Strength", blue, "The back of this cube has been stylized with a symbol of a strong man", 1022, "sprites/superstitiousbox/11tarot.png")
const hangedmancube = new Cube("XII - The Hanged Man", blue, "The back of this cube has been stylized with a man hanging from a bar by his foot.", 1149, "sprites/superstitiousbox/12tarot.png")
const deathcube = new Cube("XIII - Death", purple, "The back of this cube has been stylized with a picture of the grim reaper", 2682, "sprites/superstitiousbox/13tarot.png")
const thetowercube = new Cube("XIV - The Tower", purple, "The back of this cube has been stylized with an unstable tower", 1976, "sprites/superstitiousbox/14tarot.png")
const thedevilcube = new Cube("XV - The Devil", purple, "The back of this cube has been stylized with an artistic rendition of satan", 2854, "sprites/superstitiousbox/15tarot.png")
const temperancecube = new Cube("XVI - Temperance", purple, "The back of this cube has been stylized with a woman keeping the balance", 2511, "sprites/superstitiousbox/16tarot.png")
const thestarscube = new Cube("XVII - The Stars", orange, "The back of this cube has been stylized with a starry night sky", 5612, "sprites/superstitiousbox/17tarot.png")
const themooncube = new Cube("XVIII - The Moon", orange, "The back of this cube has been stylized with a beautiful picture of the moon", 5298, "sprites/superstitiousbox/18tarot.png")
const thesuncube = new Cube("XIX - The Sun", orange, "The back of this cube has been stylized with an artistic rendition of the sun", 3912, "sprites/superstitiousbox/19tarot.png")
const judgementcube = new Cube("XX - Judgement", red, "The back of this cube has been stylized with two men being judged", 15928, "sprites/superstitiousbox/20tarot.png")
const theworldcube = new Cube("XXI - The World", red, "The back of this cube has been stylized with the world, spinning", 13975, "sprites/superstitiousbox/21tarot.png")
const capricorncube = new Cube("Capricorn", light_green, "Patient, Strategic", 23, "sprites/superstitiousbox/capricorncube.png")
const aquariuscube = new Cube("Aquarius", light_green, "Inventive, Friendly", 12, "sprites/superstitiousbox/aquariuscube.png")
const piscescube = new Cube("Pisces", green, "Intuitive, Creative", 97, "sprites/superstitiousbox/piscescube.png")
const ariescube = new Cube("Aries", green, "Brave, Fearless", 121, "sprites/superstitiousbox/ariescube.png")
const tauruscube = new Cube("Taurus", red, "Driven, Enduring", 12953, "sprites/superstitiousbox/tauruscube.png")
const geminicube = new Cube("Gemini", blue, "Intelligent, Adaptable", 723, "sprites/superstitiousbox/geminicube.png")
const cancercube = new Cube("Cancer", blue, "Nurturing, Supportive", 558, "sprites/superstitiousbox/cancercube.png")
const leocube = new Cube("Leo", purple, "Protective, Charismatic", 2344, "sprites/superstitiousbox/leocube.png")
const virgocube = new Cube("Virgo", purple, "Humble, Orderly", 2209, "sprites/superstitiousbox/virgocube.png")
const libracube = new Cube("Libra", red, "Harmonious, Diplomatic", 11754, "sprites/superstitiousbox/libracube.png")
const scorpiocube = new Cube("Scorpio", orange, "Passionate, Determined", 3398, "sprites/superstitiousbox/scorpiocube.png")
const sagittariuscube = new Cube("Sagittarius", orange, "Lucky, Optimistic", 5891, "sprites/superstitiousbox/sagittariuscube.png")
const ophichuscube = new Cube("Ophichus", black, "The forgotten sign", 130922, "sprites/superstitiousbox/ophichuscube.png")
const ankhcube = new Cube("Ankh Cube", black, "A cube imbued with the power of egyptian gods", 149001, "sprites/superstitiousbox/ankhcube.png")
const brimstonecube = new Cube("Brimstone Cube", black, "From the fiery depths of hell, this cube has been filled with brimstone. You can feel the damned souls within screaming for repentance.", 179021, "sprites/superstitiousbox/brimstonecube.png")
const holygrailcube = new Cube("Holy Grail", black, "What? You thought the holy grail was an actual grail? It's a cup in the shape of a cube filled with holy water!", 129742, "sprites/superstitiousbox/holywatergrail.png")
const starrynightcube = new Cube("Starry Night Cube", red, "A small piece of space inside of a cube", 9812, "sprites/superstitiousbox/starrynightcube.png")

// Home box, 53 cubes
const brownbookcube                = new Cube("Brown Book Cube", light_green, "It's a completely blank, tiny book.", 10, "sprites/homebox/brownbookcube.png")
const greenbookcube                = new Cube("Green Book Cube", light_green, "It's a completely blank, tiny book.", 5, "sprites/homebox/greenbookcube.png")
const redbookcube  		         = new Cube("Red Book Cube", light_green, "It's a completely blank, tiny book.", 7, "sprites/homebox/redbookcube.png")
const lavenderbookcube             = new Cube("Lavender Book Cube", light_green, "It's a completely blank, tiny book.", 9, "sprites/homebox/lavenderbookcube.png")
const bluebedcube                  = new Cube("Blue Bed Cube", light_green, "This... is a small bed!", 12, "sprites/homebox/bluebedcube.png")
const redbedcube                   = new Cube("Red Bed Cube", light_green, "This... is a small bed!", 14, "sprites/homebox/redbedcube.png")
const yellowbedcube                = new Cube("Yellow Bed Cube", light_green, "This... is a small bed!", 16, "sprites/homebox/yellowbedcube.png")
const purplebedcube                = new Cube("Purple Bed Cube", light_green, "This... is a small bed!", 18, "sprites/homebox/purplebedcube.png")
const greenbedcube                 = new Cube("Green Bed Cube", light_green, "This... is a small bed!", 20, "sprites/homebox/greenbedcube.png")
const bluewashingmachinecube       = new Cube("Blue Washing Machine Cube", green, "A tiny, functioning, washing machine... but why?", 100, "sprites/homebox/bluewashingmachinecube.png")
const greenwashingmachinecube      = new Cube("Green Washing Machine Cube", green, "A tiny, functioning, washing machine... but why?", 141, "sprites/homebox/greenwashingmachinecube.png")
const washingmachinecube           = new Cube("Washing Machine Cube", green, "A tiny, functioning, washing machine... but why?", 237, "sprites/homebox/washingmachinecube.png")
const pinkwashingmachinecube       = new Cube("Pink Washing Machine Cube", green, "A tiny, functioning, washing machine... but why?", 110, "sprites/homebox/pinkwashingmachinecube.png")
const redwashingmachinecube        = new Cube("Red Washing Machine Cube", green, "A tiny, functioning, washing machine... but why?", 90, "sprites/homebox/redwashingmachinecube.png")
const glassofwatercube             = new Cube("Glass Of Water", green, "A glass of water, ready to drink! don't drink it tho..", 334, "sprites/homebox/glassofwatercube.png")
const glassofwinecube              = new Cube("Glass Of Wine", green, "A glass of wine, ready to drink! don't drink it tho..", 381, "sprites/homebox/glassofwinecube.png")
const glassofsodacube              = new Cube("Glass Of Soda", green, "A glass of soda, ready to drink! don't drink it tho..", 334, "sprites/homebox/glassofsodacube.png")
const greentoastercube             = new Cube("Green Toaster Cube", blue, "A real, tiny toaster that actually works! Finally! You can toast your little bits of bread everyone just has lying around!", 708, "sprites/homebox/greentoastercube.png")
const purpletoastercube            = new Cube("Purple Toaster Cube", blue, "A real, tiny toaster that actually works! Finally! You can toast your little bits of bread everyone just has lying around!", 748, "sprites/homebox/purpletoastercube.png")
const redtoastercube               = new Cube("Red Toaster Cube", blue, "A real, tiny toaster that actually works! Finally! You can toast your little bits of bread everyone just has lying around!", 588, "sprites/homebox/redtoastercube.png")
const toastercube                  = new Cube("Toaster Cube", blue, "A real, tiny toaster that actually works! Finally! You can toast your little bits of bread everyone just has lying around!", 908, "sprites/homebox/toastercube.png")
const bluetoastercube              = new Cube("Blue Toaster Cube", blue, "A real, tiny toaster that actually works! Finally! You can toast your little bits of bread everyone just has lying around!", 668, "sprites/homebox/bluetoastercube.png")
const bluehousecube                = new Cube("Blue House", green, "A small house for your tiny little gnomes!", 471, "sprites/homebox/bluehousecube.png")
const greenhouse                   = new Cube("Green House", green, "A small house for your tiny little gnomes!", 422, "sprites/homebox/greenhousecube.png")
const pinkhouse                    = new Cube("Pink House", green, "A small house for your tiny little gnomes!", 498, "sprites/homebox/pinkhousecube.png")
const yellowhouse                  = new Cube("Yellow House", green, "A small house for your tiny little gnomes!", 439, "sprites/homebox/yellowhousecube.png")
const purpletablecube              = new Cube("Purple Table Cube", blue, "Its a small table; reminds you of the little tables with the pizzas that you get? You know those? Right?", 541, "sprites/homebox/purpletablecube.png")
const redtablecube                 = new Cube("Red Table Cube", blue, "Its a small table; reminds you of the little tables with the pizzas that you get? You know those? Right?", 543, "sprites/homebox/redtablecube.png")
const bluetablecube                = new Cube("Blue Table Cube", blue, "Its a small table; reminds you of the little tables with the pizzas that you get? You know those? Right?", 542, "sprites/homebox/bluetablecube.png")
const greentablecube               = new Cube("Green Table Cube", blue, "Its a small table; reminds you of the little tables with the pizzas that you get? You know those? Right?", 548, "sprites/homebox/greentablecube.png")
const browntablecube               = new Cube("Table Cube", blue, "Its a small table; reminds you of the little tables with the pizzas that you get? You know those? Right?", 761, "sprites/homebox/browntable.png")
const confusedcube                 = new Cube("Confused Cube", purple, "What? What do you want me to do? It's just bad luck, not a bug.", 982, "sprites/homebox/confusedcube.png")
const deadcube                     = new Cube("Dead Cube", purple, "That feel when you get baited", 832, "sprites/homebox/deadcube.png")
const dizzycube                    = new Cube("Dizzy Cube", purple, "Don't zoom too far in while the jackpot is spinning..", 412, "sprites/homebox/dizzycube.png")
const happycube                    = new Cube("Happy Cube", purple, "When you don't pull this item", 762, "sprites/homebox/happycube.png")
const hungrycube                   = new Cube("Hungry Cube", purple, "When you finally win a jackpot", 195, "sprites/homebox/hungrycube.png")
const sadcube                      = new Cube("Sad Cube", purple, "Losing your all-in be like", 573, "sprites/homebox/sadcube.png")
const sleepycube                   = new Cube("Sleepy Cube", purple, "When you guys report a nonexistent bug to me, complaining about bad odds", 882, "sprites/homebox/sleepycube.png")
const straightfacecube             = new Cube("Straight Faced Cube", purple, "When you guys tell me about the 15 jackpot losses in a row", 702, "sprites/homebox/straightfacecube.png")
const dogcube                      = new Cube("Dog Cube", orange, "Cute dog! but like a square..?", 5721, "sprites/homebox/dogcube.png") //prices are identical in order to avoid the cats vs. dogs debate
const catcube                      = new Cube("Cat Cube", orange, "Yup, plastic/rubber cat!", 5721, "sprites/homebox/catcube.png")
const astroturfcube                = new Cube("Astro-turf Cube", orange, "This green grass will be the envy of the neighbourhood when you get about 9000+ more of them to cover your entire yard!", 4285, "sprites/homebox/astroturfcube.png")
const alarmcube                    = new Cube("Alarm Cube", black, "This is the most annoying thing ever, and the second hardest thing you hit in the morning ( ͡° ͜ʖ ͡°)", 94812, "sprites/homebox/alarmcube.png")
const grandpasrelic                = new Cube("Grandpa's Relic", black, "This was found in the attic... why did he hide this?", 223019, "sprites/homebox/grandpasrelic.png")
const fridgecube                   = new Cube("Fridge Cube", red, "Theres lots of cool (literally and figuratively) inside!", 9023, "sprites/homebox/fridgecube.png")
const laptopcube                   = new Cube("Laptop Cube", red, "A tiny, functioning laptop! only like 3MB of RAM, though.", 8691, "sprites/homebox/laptopcube.png")
const desktopcube                  = new Cube("Desktop Cube", red, "A desktop computer, no monitor! It says it has 2GB of memory.", 9701, "sprites/homebox/desktopcube.png")
const microwavecube                = new Cube("Microwave Cube", red, "Ah yes, the microwave; a classic staple of college dorm life and the ultimate popcorn-popper.", 6912, "sprites/homebox/microwavecube.png")
const monitorcube                  = new Cube("Monitor Cube", red, "A tiny monitor to go with the tiny desktop computer you may/may not have!", 7812, "sprites/homebox/monitorcube.png")
const ovencube                     = new Cube("Oven Cube", red, "Cooks tiny bacon!", 5902, "sprites/homebox/ovencube.png")
const itcries                      = new Cube("It Cries", black, "A small, crying ghost-thing..?", 102933, "sprites/homebox/itcriescube.png")
const gildedcube                   = new Cube("Gilded Cube", black, "A highly stylized ivory decorative cube.", 132723, "sprites/homebox/gildedcube.png")
const tvcube                       = new Cube("TVCube", black, "A small, very high quality TV! doesnt even require a cable subscription to use!", 139372, "sprites/homebox/TVcube.png")
// game box
const geometrydashcube= new Cube("Geometry Dash Cube", light_green, "A truly OG timing-based progression game, geometry dash blends interesting mechanics with consistent and challenging platforming", 581, "sprites/gamebox/geometrydashcube.png")
const robloxcube= new Cube("Roblox Cube", light_green, "BE ANYTHING, BUILD ANYTHING! (but you have to pay for both)", 561, "sprites/gamebox/robloxcube.png")
const keyboardcube= new Cube("Keyboard Cube", green, "A cube covered in keyboard keys... but there is no escape key.", 920, "sprites/gamebox/keyboardcube.png")
const devildaggerscube= new Cube("Devil Daggers Cube", green, "A game about optimization and skill, Devil Daggers presents its players with a weak character and very strong enemies. (not to mention the competitive aspect of having a scoreboard for everyone to see.)", 1174, "sprites/gamebox/devildaggerscube.png")
const controllercube= new Cube("Controller Cube", green, "It's a classic Xbox controller", 923, "sprites/gamebox/controllercube.png")
const inspirationi= new Cube("Inspiration I", black, "The front-end developer of the games that inspired this one, go check him out! <br/> Banned", 324012, "sprites/gamebox/bannedcube.png")
const inspirationii= new Cube("Inspiration II", black, "The back end developer of one of the games that inspired this one, go check him out! <br/> Roflzilla", 324012, "sprites/gamebox/roflzillacube.png")
const grassblockcube= new Cube("Minecraft Cube", red, "One of the greatest masterpieces of gaming ever, this game has managed to survive more than one decade of cultural shifts with its insane replayability.", 79282, "sprites/gamebox/grassblockcube.png")
const asepritecube = new Cube("Aseprite Cube", blue, "A great program I use to make the cubes in this game!", 3012, "sprites/gamebox/asepritecube.png")
const battleblockcube = new Cube("Battle Block Theatre Cube", blue, "One of the best games to play with friends", 3692, "sprites/gamebox/bbcube.png")
const enterthegungeoncube = new Cube("Enter the Gungeon Cube", blue, "Enter the Gungeon is one of my personal favorite roguelikes, with a high skill ceiling, tight gameplay, and satisfying achievements.", 3976, "sprites/gamebox/etgcube.png")
const halflifecube = new Cube("Half Life Cube", black, "Half life is one of Valve's masterpieces, the pinnacle of a great puzzle-solving game with interesting mechanics and engaging story elements... but there isn't a third one.", 400211, "sprites/gamebox/hlcube.png")
const hollowknightcube = new Cube("Hollow Knight Cube", black, "Hollow Knight is the breakout success from Team Cherry; the game was on kickstarter, exceeding its goal very quickly. One of the best metroidvanias out there, it truly defines the genre.", 229895, "sprites/gamebox/hollowknightcube.png")
const theendisnighcube = new Cube("The End Is Nigh Cube", purple, "A hard as nails platformer, the end is nigh is another game by the creator of Super Meat Boy; so you can bet this game has tight controls and a strong sense of personality", 5482, "sprites/gamebox/teincube.png")
const oneshotcube = new Cube("OneShot Cube", purple, "A relatively short puzzle game, this narrative masterpiece takes the norms of a puzzle game and changes it by making you god.", 3353, "sprites/gamebox/oneshotcube.png")
const portalcube = new Cube("Portal Cube", red, "Another of Valve's great works, portal is a puzzle solving game with tons of personality, and mind-bending puzzles.", 69696, "sprites/gamebox/portalcube.png")
const thebindingofisaaccube = new Cube("The Binding Of Isaac Cube", black, "One of the best roguelikes out there, The Binding of Isaac juxtaposes the innocence of a child with the crushing reality of a hard upbringing, and an overarching narrative of religion.", 251922, "sprites/gamebox/tboicube.png")
const teamfortresstwocube = new Cube("Team Fortress 2 Cube", black, "hands-down the best class based shooter of all time, TF2 mixes personality with super strong gameplay. Not to mention the community behind it; being one of the strongest for a game that is more than 10 years old!", 449129, "sprites/gamebox/tf2cube.png")
const starboundcube = new Cube("Starbound Cube", orange, "I would say that this game is one of my all-time favorites, HOWEVER, it is my all-time favorite disappointment. This game released with lots of bugs, shitty gameplay, and a frustrating to follow storyline. The base game is actual ass. BUUUUT the mods for this game make it so much fun, so try it", 30029, "sprites/gamebox/sboundcube.png")
const undertalecube = new Cube("Undertale Cube", black, "A groundbreaking roleplaying game with a shit ton of personality and content, this game defines the idea of a perfect lifelong work.", 379172, "sprites/gamebox/undertalecube.png")
const hyperlightdriftercube = new Cube("Hyper Light Drifter Cube", orange, "At first confusing, this game allows the player to go on a journey of difficult to master, skill-based movement and combat. The learning curve is kinda steep though.", 45922, "sprites/gamebox/hldcube.png")
const tabscube = new Cube("T.A.B.S. Cube", orange, "Totally Accurate Battle Simulator is a game that popularized the physics based battle genre that spawned or inspired other games like Besiege and Stick Fight: The Game. Its basic premise is that you are a commander that commands an army of physics based warriors. The encounters are funny, and the physics make its hilarity a cornerstone of strategical comedy. <br/> suggested by Epitaxia", 35723, "sprites/gamebox/tabscube.png")
const halocube = new Cube("Halo Cube", red, "Halo is the Xbox's opening title. Developed by microsoft, Halo has been a huge part of first person shooter games, probably up there with DOOM. <br/> suggested by Roflzilla", 59832, "sprites/gamebox/halocube.png")
const gmodcube = new Cube("Garry's Mod Cube", green, "Garry's Mod is a game (which is actually a mod, big surprise) that has cemented iteself as an almost perfect sandbox game. This game has spawned many games, gamemodes, and absolutely hilarious animations. (anyone out there know kitty0706?) <br/> suggested by ForrestGump", 1283, "sprites/gamebox/gmodcube.png")
//= new Cube("name", rarity, "flavortext", price, "sprites/.png")

// special reward cubes
fiveheadcube = new Cube("5head Cube", purple, "Stupid 5head!", 7812, "sprites/twitchbox/4headcube.png")
allcubes.pop()
clowncube = new Cube("Clown Cube", black, "Literally you, right now. <br/> by ForrestGump", 223081, "sprites/twitchbox/clowncube.png")
allcubes.pop()
feelsbadmancube = new Cube("Feelsbadman Cube", orange, "That feels bad, man", 17120, "sprites/twitchbox/feelsbadmancube.png")
allcubes.pop()
brokenemotecube = new Cube("Broken Emote..?", black, "I don't know... did I upload the wrong file? <br/> by Arachnix", 259999, "sprites/twitchbox/Idk_a_name_yet.gif")
allcubes.pop()
isaaccube = new Cube("Isaac!", purple, "Isaac and his mother lived on a house on a hill...", 7321, "sprites/twitchbox/isaacemote.png")
allcubes.pop()
kappacube = new Cube("Kappa Cube", orange, ":kappa:", 17823, "sprites/twitchbox/kappacube.png")
allcubes.pop()
monkaScube = new Cube("MonkaS Cube", red, "the suspense!", 59318, "sprites/twitchbox/monkaScube.png")
allcubes.pop()
omegalulcube = new Cube("Omegalul Cube", purple, "LUL", 7938, "sprites/twitchbox/omegalulcube.png")
allcubes.pop()
pepecube = new Cube("Pepe Cube", black, "A classic", 401820, "sprites/twitchbox/pepecube.png")
allcubes.pop()
pogcube = new Cube("Pog Cube", purple, "..and then he turned into poggers. Funniest shit I've ever seen.", 7185, "sprites/twitchbox/pogcube.png")
allcubes.pop()
poggerscube = new Cube("Poggers Cube", red, "The real poggers!", 49283, "sprites/twitchbox/poggerscube.png")
allcubes.pop()
twitchbotanguish = new Cube("Anguished Twitch Bot", light_green, "D:", 500, "sprites/twitchbox/twitchbotanguish.png")
allcubes.pop()
twitchbotcool = new Cube("Cool Twitch Bot", green, "B)", 1000, "sprites/twitchbox/twitchbotcool.png")
allcubes.pop()
twitchbothappy = new Cube("Happy Twitch Bot", blue, ":D / :)", 2000, "sprites/twitchbox/twitchbothappy.png")
allcubes.pop()
twitchbotkindasad = new Cube("Kinda Sad Twitch Bot", green, "Kinda sad doe.", 1000, "sprites/twitchbox/twitchbotkindasad.png")
allcubes.pop()
twitchbotp = new Cube(":P Twitch Bot", light_green, ":P", 500, "sprites/twitchbox/twitchbotp.png")
allcubes.pop()
twitchbotsad = new Cube("Sad Twitch Bot", green, ":(", 1000, "sprites/twitchbox/twitchbotsad.png")
allcubes.pop()
twitchbotstraightface = new Cube("Straight Faced Twitch Bot", blue, ":|", 2000, "sprites/twitchbox/twitchbotstraightface.png")
allcubes.pop()
twitchbotsurprised = new Cube("Surprised Twitch Bot", light_green, ":O", 500, "sprites/twitchbox/twitchbotsurprised.png")
allcubes.pop()
twitchbotwinking = new Cube("Winking Twitch Bot", blue, ";)", 2000, "sprites/twitchbox/twitchbotwinking.png")
allcubes.pop()
twitchbotwut = new Cube("Wut? Twitch Bot", light_green, "O.o", 500, "sprites/twitchbox/twitchbotwut.png")
allcubes.pop()
twitchheart = new Cube("Twitch Heart", blue, "<3", 2000, "sprites/twitchbox/twitchheart.png")
allcubes.pop()

// slime box
goldslimecube = new Cube('Gold Slime Cube', red, 'Pretty Pretty!', 51982, "sprites/slimebox/goldslimecube.png")
allcubes.pop()
goldslimejar = new Cube('Gold Slime Jar', black, 'he looks pretty content in there!', 161339, "sprites/slimebox/goldslimejar.png")
allcubes.pop()
greengoocube = new Cube('Green Goo Cube', light_green, 'eeew. this is gross.', 30, "sprites/slimebox/greengoocube.png")
allcubes.pop()
greenslimecube = new Cube('Green Slime Cube', blue, 'look at this little guy!', 501, "sprites/slimebox/greenslimecube.png")
allcubes.pop()
greenslimejar = new Cube('Green Slime Jar', orange, 'ready for experimentation!', 12839, 'sprites/slimebox/greenslimejar.png')
allcubes.pop()
noirslimecube = new Cube('Noir Slime', purple, 'can only see in black and white, but is fine with that', 3210, 'sprites/slimebox/noirslimecube.png')
allcubes.pop()
pinkslimejar  = new Cube('Pink Slime Jar', orange, 'ready for manipulation!', 10297, 'sprites/slimebox/pinkslimejar.png')
allcubes.pop()
purplegoocube  = new Cube('Purple Goo Cube', green, 'yuck.', 40, 'sprites/slimebox/purplegoocube.png')
allcubes.pop()
purpleslimecube  = new Cube('Purple Slime Cube', blue, 'very nice little guy', 525, 'sprites/slimebox/purpleslimecube.png')
allcubes.pop()
purpleslimejar  = new Cube('Purple Slime Jar', orange, 'ready for alteration!', 9971, 'sprites/slimebox/purpleslimejar.png')
allcubes.pop()
redgoocube = new Cube('Red Goo Cube', light_green, 'smells like a big ole poopie.', 1, 'sprites/slimebox/redgoocube.png')
allcubes.pop()
redslimecube = new Cube('Red Slime Cube', purple, 'blobulon? barely even know her!', 3719, 'sprites/slimebox/redslimecube.png')
allcubes.pop()
redslimejar = new Cube('Red Slime Jar', red, 'he seems scared.. or surprised?', 37833, 'sprites/slimebox/redslimejar.png')
allcubes.pop()
yellowgoocube = new Cube('Yellow Goo Cube', green, 'pee. urine. piss.', 23, "sprites/slimebox/yellowgoocube.png")
allcubes.pop()
yellowslimecube = new Cube('Yellow Slime Cube', purple, 'pee slime.', 1683, "sprites/slimebox/yellowslimecube.png")
allcubes.pop()
yinyangslime = new Cube('Yin-Yang Slime', black, 'Perfectly balanced...', 193466, 'sprites/slimebox/yinyangslime.png')
allcubes.pop()
// food box 1
breadcube = new Cube('Bread Cube', light_green, 'I am bread!!', 16, 'sprites/foodbox/breadcube.png')
toastcube = new Cube('Toast Cube', green, 'Bread: cooked twice', 59, 'sprites/foodbox/toastcube.png')
wafflecube = new Cube('Waffle Cube', blue, 'Do you like waffles?! <br/> Yeah we like waffles!', 402, 'sprites/foodbox/wafflecube.png')
pancakecube = new Cube('Pancake Cube', purple, 'Do you like pancakes? <br/> Yeah we like pancakes!', 1102, 'sprites/foodbox/pancakecube.png')
sushicube = new Cube('Sushi Cube', red, 'Get this: it is seafood wrapped in seafood with rice padding!', 20184, 'sprites/foodbox/sushicube.png')
eggcube = new Cube('Egg Cube', orange, 'The egg came first!', 9729, 'sprites/foodbox/eggcube.png')
chickencube = new Cube('Chicken Cube', purple, 'Cringe; didnt come first', 1401, 'sprites/foodbox/chickencube.png')
tacocube = new Cube('Taco Cube', green, 'Taco bout a cringe joke', 90, 'sprites/foodbox/tacocube.png')
burritocube = new Cube('Burrito Cube', blue, 'Taco but better in every way.', 391, 'sprites/foodbox/burritocube.png')
lettucecube = new Cube('Lettuce Cube', green, 'Crumchy veggie', 74, 'sprites/foodbox/lettucecube.png')
beancube = new Cube('Bean Cube', light_green, 'Beens r gud', 11, 'sprites/foodbox/beancube.png')
guacamolecube = new Cube('Guacamole Cube', blue, 'Holy Guacamole!', 499, 'sprites/foodbox/guacamolecube.png')
canofgarbanzobeans = new Cube('Can Of Garbanzo Beans', light_green, '', 0, 'sprites/foodbox/canofgarbanzobeans.png')
saltinecube = new Cube('Saltine Cube', orange, 'Its that weird cracker you get with your tomato soup at some restaurants!', 5918, 'sprites/foodbox/saltinecube.png')
crumbycube = new Cube('Crumby Cube', light_green, 'Where is the rest of the cube?!', 3, 'sprites/foodbox/crumbycube.png')
cupcakecube = new Cube('Cupcake Cube', red, 'Cake but smaller, presumably able to fit into a cup', 18293, 'sprites/foodbox/cupcakecube.png')
sandwichcube = new Cube('Sandwich Cube', purple, 'Why are you selling?! Is only ham!', 1388, 'sprites/foodbox/sandwichcube.png')
burntchickennuggetcube = new Cube('Burnt Chicken Nugget', green, 'I still love myself', 25, 'sprites/foodbox/burntchickennuggetcube.png')
chickennuggetcube = new Cube('Chicken Nugget', red, 'its nuggie time!', 17202, 'sprites/foodbox/chickennuggetcube.png')
prisoncakecube = new Cube('Prison Cake Cube', black, 'Contains sharp object not for prison.', 149480, 'sprites/foodbox/prisoncakecube.png')
bakedpotatocube = new Cube('Baked Potato Cube', black, 'Potato but with extra goodness!', 270319, 'sprites/foodbox/bakedpotatocube.png')
ricecube = new Cube('Rice Cube', blue, 'The perfect base to any savory dish!', 502, 'sprites/foodbox/ricecube.png')
dumplingcube = new Cube('Dumpling Cube', orange, 'Takin a dump in the dumpling is not allowed!', 4838, 'sprites/foodbox/dumplingcube.png')
gumcube = new Cube('Gum Cube', red, 'This is good, unless theres rice near it, then it becomes a pretentious POS', 12220, 'sprites/foodbox/gumcube.png')
finewinecube = new Cube('Fine Wine Cube', purple, 'Like fine wine, [YOUR JOKE HERE] gets better with age!', 1599, 'sprites/foodbox/finewinecube.png')
tounguecube = new Cube('Toungue Cube', light_green, 'EEEEEEEEEEEEEEEEW!!! YOU NASTY MAN!!!', 0, 'sprites/foodbox/tounguecube.png')
// keyboard box, rarities scale based on least common-most common pressed/used in this .js file
acube = new Cube('A', light_green, 'The A key', 20, 'sprites/keyboardbox/akey.png')
bcube = new Cube('B', light_green, 'The B key', 31, 'sprites/keyboardbox/bkey.png')
ccube = new Cube('C', light_green, 'The C key', 60, 'sprites/keyboardbox/ckey.png')
dcube = new Cube('D', light_green, 'The D key', 48, 'sprites/keyboardbox/dkey.png')
ecube = new Cube('E', green, 'The E key', 122, 'sprites/keyboardbox/ekey.png')
fcube = new Cube('F', green, 'The F key', 105, 'sprites/keyboardbox/fkey.png')
gcube = new Cube('G', green, 'The G key', 130, 'sprites/keyboardbox/gkey.png')
hcube = new Cube('H', green, 'The H key', 197, 'sprites/keyboardbox/hkey.png')
icube = new Cube('I', blue, 'The I key', 444, 'sprites/keyboardbox/ikey.png')
jcube = new Cube('J', blue, 'The J key', 404, 'sprites/keyboardbox/jkey.png')
kcube = new Cube('K', blue, 'The K key', 609, 'sprites/keyboardbox/kkey.png')
lcube = new Cube('L', blue, 'The L key', 820, 'sprites/keyboardbox/lkey.png')
mcube = new Cube('M', purple, 'The M key', 1577, 'sprites/keyboardbox/mkey.png')
ncube = new Cube('N', purple, 'The N key', 1202, 'sprites/keyboardbox/nkey.png')
ocube = new Cube('O', purple, 'The O key', 974, 'sprites/keyboardbox/okey.png')
pcube = new Cube('P', purple, 'The P key', 1308, 'sprites/keyboardbox/pkey.png')
qcube = new Cube('Q', orange, 'The Q key', 33022, 'sprites/keyboardbox/qkey.png')
rcube = new Cube('R', orange, 'The R key', 14712, 'sprites/keyboardbox/rkey.png')
scube = new Cube('S', orange, 'The S key', 65683, 'sprites/keyboardbox/skey.png')
tcube = new Cube('T', orange, 'The T key', 82183, 'sprites/keyboardbox/tkey.png')
ucube = new Cube('U', red, 'The U key', 90110, 'sprites/keyboardbox/ukey.png')
vcube = new Cube('V', red, 'The V key', 99230, 'sprites/keyboardbox/vkey.png')
wcube = new Cube('W', red, 'The W key', 95694, 'sprites/keyboardbox/wkey.png')
xcube = new Cube('X', black, 'The X key', 140130, 'sprites/keyboardbox/xkey.png')
ycube = new Cube('Y', black, 'The Y key', 198565, 'sprites/keyboardbox/ykey.png')
zcube = new Cube('Z', black, 'The Z key', 149999, 'sprites/keyboardbox/zkey.png')
zcube = new Cube('.', black, 'The . key', 159999, 'sprites/keyboardbox/periodkey.png')
// Mythical Materials
lead = new Cube('Lead', light_green, 'do not put your mouth on this.', 0, 'sprites/mythicalmaterials/lead.png')
lightstone = new Cube('Lightstone', green, 'super durable, emits light and shatters into dust under immense heat', 1396, 'sprites/mythicalmaterials/lightstone.png')
demonsteel = new Cube('Demonsteel', green, 'highly heat resistant, this metal is used by hells armies to take entire cities in minutes', 998, 'sprites/mythicalmaterials/demonsteel.png')
aerothread = new Cube('Aerothread', blue, 'an extremely stretchy string, aerothread is used in planet-pulleys', 2084, 'sprites/mythicalmaterials/aerothread.png')
deliriumtitanium = new Cube('Delirium Titanium', purple, 'a very odd alloy, those struck by weapons of this metal are afflicted with terrible night terrors.', 5833, 'sprites/mythicalmaterials/deliriumcube.png')
beamdust = new Cube('Beam Dust', blue, 'beam dust is light that has been cracked and collected, it is very bright and light.', 1928, 'sprites/mythicalmaterials/beamdust.png')
solarnickel = new Cube('Solar Nickel', orange, 'a metal harvested from the core of a star, it pulses with undying heat.', 39217, 'sprites/mythicalmaterials/solarnickel.png')
cratersoil = new Cube('Cratersoil', green, 'special dirt that is so fertile, anything can grow upon it', 943, 'sprites/mythicalmaterials/cratersoil.png')
quakecopper = new Cube('Quake Copper', blue, 'copper that has an interesting property: it shakes on its own!', 1752, 'sprites/mythicalmaterials/quakecopper.png')
planarsilk = new Cube('Planar Silk', red, 'an unimaginably powerful material, planar silk can see into other planes and dimensions, peeking into different realities and times.', 76231, 'sprites/mythicalmaterials/planarsilk.png')
spectralwood = new Cube('Spectralwood', purple, 'this haunted wood serves as a way to communicate with the spirits of the dead.', 6502, 'sprites/mythicalmaterials/spectralwood.png')
crowncobalt = new Cube('Crown Cobalt', blue, 'this weird metal is very easy to form and shape; making it perfect for clothing', 1915, 'sprites/mythicalmaterials/crowncobalt.png')
dreamclay = new Cube('Dream Clay', orange, 'the properties of this material are not fully understood, however, it is known that placing a lump onto somebodys head creates a 3 dimensional image of what they are thinking about', 44330, 'sprites/mythicalmaterials/dreamclay.png')
chronomarble = new Cube('Chronomarble', black, 'this material has the ability to go back and forth in time, and has the unique ability to alter the future.', 562027, 'sprites/mythicalmaterials/chronomarble.png')
utopiancotton = new Cube('Utopian Cotton', orange, 'this cotton is the most perfect and comfortable cotton in the world!', 28533, 'sprites/mythicalmaterials/utopiancotton.png')
corruptresin = new Cube('Corrupt Resin', green, 'despite being very tasty, corrupt resin is very heat-resistant', 774, 'sprites/mythicalmaterials/corruptresin.png')
lovesand = new Cube('Love Sand', black, 'love sand is one of the most psychoreactive elements of the universe, able to read and alter beings moods depending on its state', 514235, 'sprites/mythicalmaterials/lovesand.png')
electricfleece = new Cube('Electric Fleece', red, 'able to generate and expel electricity, electric fleece was banned throughout many planets for its dangerous applications in pranks', 89482, 'sprites/mythicalmaterials/electricfleece.png')
fortunecloth = new Cube('Fortune Cloth', purple, 'able to accurately predict fortunes, but only has one use before desintegrating', 7701, 'sprites/mythicalmaterials/fortunecloth.png')
borderstone = new Cube('Borderstone', orange, 'when exposed to extreme cold, borderstone freezes itself in time and space', 40001, 'sprites/mythicalmaterials/borderstone.png')
enchantednylon  = new Cube('Enchanted Nylon', black, 'most durable, energy-absorbing, and breathable clothing material in the universe, it feels like walking around naked even though a bullet in the back would feel like a light tap', 587255, 'sprites/mythicalmaterials/enchantednylon.png')
moltenzinc = new Cube('Molten Zinc', blue, 'very, very hot zinc that never, ever cools off!', 1399, 'sprites/mythicalmaterials/moltenzinc.png')
edgebrass = new Cube('Edgebrass', red, 'brass that can be sharpened to any thickness. master swordsmiths have been able to make blades that can fly though torsos as fast as the air', 79999, 'sprites/mythicalmaterials/edgebrass.png')
warpedsilver = new Cube('Warped Silver', red, 'silver that has been sharpened and twisted by magnets, extremely dangerous.', 29999, 'sprites/mythicalmaterials/warpedsilver.png')
// gold Cubes
const adamantiumcube = new Cube("Adamantium Cube", yellow, "A small piece of the rarest metal on earth.", 1539843, "sprites/golds/adamantiumcube.png")
const bluenebulacube = new Cube("Hydrogen Nebula Cube", yellow, "The hydrogen nebula, masterfully recreated in a glass cube", 1349273, "sprites/golds/bluenebulacube.png")
const cakecube = new Cube("Cake Cube", yellow, "A nice, delicious, tiny cake", 1294720, "sprites/golds/cakecube.png")
const goldendicecube = new Cube("Golden D6", yellow, "Garunteed sixes.", 1784921, "sprites/golds/goldendice.png")
const goldmushroomcube = new Cube("Gold Mushroom", yellow, "A highly sought after prize of fungi", 1596390, "sprites/golds/goldmushroomcube.png")
const goldophichuscube = new Cube("Golden Ophichus", yellow, "Ophichus' lament", 976590, "sprites/golds/goldophichuscube.png")
const illuminaticube = new Cube("Illuminati Cube", yellow, "Does this cube even exist?", 1696969, "sprites/golds/illuminaticube.png")
const smashbroscube = new Cube("Super Smash Bros. Cube", yellow, "Super Smash Bros. is the ultimate fighting game, using everyone's favorite characters in an all-out battle against evil.. and your friends!", 1897122, "sprites/golds/smashbroscube.png")
const smwcube = new Cube("Super Mario World Cube", yellow, "Super Mario World is the best mario game. Hands down.", 1759275, "sprites/golds/smwcube.png")
const spherecube = new Cube("A Sphere?", yellow, "...", 1739573, "sprites/golds/spherecube.png")
const truereliccube = new Cube("The True Relic", yellow, "The real relic, washed of all its sins", 1882372, "sprites/golds/truerelic.png")
const rubycube = new Cube("Ruby Cube", yellow, "like red diamonds!", 887132, "sprites/golds/rubycube.png")
const goldpepecube = new Cube("Golden Pepe Cube", yellow, "all hail pepe", 2819239, "sprites/golds/goldpepecube.png")
allcubes.pop()
const twitchcube = new Cube("Twitch Cube", yellow, "...", 1587132, "sprites/golds/twitchcube.png")
allcubes.pop()
const cookieslimecube = new Cube("Cookie Slime Cube", yellow, "mmmMmmMmmmmMMmmmmm cuukee", 990172, "sprites/golds/cookieslimecube.png")
allcubes.pop()
const smugslimecube = new Cube("Smug Slime Cube", yellow, "wait did you see that?", 1401722, "sprites/golds/smugslime.gif")
allcubes.pop()
const underscorecube = new Cube("_", yellow, "The _ key", 902502, "sprites/keyboardbox/underscorekey.png")
const slashcube = new Cube("/", yellow, "The / key", 858732, "sprites/keyboardbox/slashkey.png")
const tildecube = new Cube("~", yellow, "The ~ key", 971125, "sprites/keyboardbox/tildekey.png")
const interdimensionalseal = new Cube("Interdimensional Seal", yellow, "Tastes like toothpaste...", 1102900, "sprites/interdimensionalseal.png")
const donutcube = new Cube("Donut Cube", yellow, "delicious. finally; some good food.", 1001722, "sprites/foodbox/donutcube.png")
const dragonglass = new Cube("Dragonglass", yellow, "ridiculously expensive, environmentally safe alternative to neutron fuel", 2106426, 'sprites/mythicalmaterials/dragonglass.png')
const fortunebone = new Cube("Fortunebone", yellow, "part of an ancient being that turned everything he touched into gold.", 1900138, 'sprites/mythicalmaterials/fortunebone.png')
// = new Cube()
