function addprefix(namespace, bonus, rarity) {
	namespace = namespace.charAt(0).toUpperCase()+ namespace.substring(1);
	allPrefixes.push({namespace: namespace, bonus: bonus, rarity: rarity})
}
allPrefixes = []

addprefix("lamentable", 0.6, green)
addprefix("jealous", 0.9, light_green)
addprefix("crazy", 1.1, blue)
addprefix("bouncy", 1, green)
addprefix("questionable", 1, light_green)
addprefix("stingy", 0.8, light_green)
addprefix("serious", 1.05, green)
addprefix("safe", 1.1, blue)
addprefix("fearful", 0.99, light_green)
addprefix("ripe", 0.8, light_green)
addprefix("panicky", 0.7, light_green)
addprefix("jazzy", 1.7, orange)
addprefix("terrific", 1.3, purple)
addprefix("female", 1.1, blue)
addprefix("male", 1.1, blue)
addprefix("ritzy", 1.5, orange)
addprefix("ultra", 1.2, blue)
addprefix("thin", 0.9, green)
addprefix("jaded", 0.95, light_green)
addprefix("obtainable", 1, light_green)
addprefix("fragile", 0.5, light_green)
addprefix("ambiguous", 1, green)
addprefix("indifferent", 1, green)
addprefix("unreal", 2, red)
addprefix("mythical", 2.3, black)
addprefix("godly", 1.9, red)
addprefix("coordinated", 1, green)
addprefix("gruesome", 0.9, light_green)
addprefix("ugliest", 0.5, orange)
addprefix("itchy", 0.95, green)
addprefix("unsightly", 0.9, light_green)
addprefix("luxurious", 1.6, orange)
addprefix("defective", 0.1, black)
addprefix("ashamed", 0.9, light_green)
addprefix("glorious", 2.1, black)
addprefix("sexual", 1.2, purple)
addprefix("decent", 1.1, purple)
addprefix("talented", 1.1, blue)
addprefix("idiotic", 0.8, light_green)
addprefix("snobbish", 0.9, green)
addprefix("legendary", 1.8, red)
addprefix("debonair", 1.2, blue)
addprefix("weak", 0.7, light_green)
addprefix("strong", 1.3, purple)
addprefix("unlikely", 1.7, orange)
addprefix("fumbling", 1, green)
addprefix("unique", 0.99, green)
addprefix("grotesque", 0.9, light_green)
addprefix("steadfast", 1.2, blue)
addprefix("chivalrous", 1.5, purple)
addprefix("stimulating", 1.3, blue)
addprefix("healthy", 1.1, green)
addprefix("redundant", 1, green)
addprefix("productive", 1.3, purple)
addprefix("pentient", 0.9, light_green)
addprefix("rebellious", 1.1, light_green)
addprefix("delicious", 1.6, purple)
addprefix("stale", 0.9, light_green)
addprefix("brave", 1.3, purple)
addprefix("tough", 1.1, green)
addprefix("naughty", 0.9, light_green)
addprefix("puzzling", 1.6, orange)
addprefix("heavenly", 2.1, black)
addprefix("sloppy", 0.9, light_green)
addprefix("freezing", 1.1, green)
addprefix("worthless", 0, light_green) // this is gonna piss someone off hehe
addprefix("abhorrent", 0.7, light_green)
addprefix("zany", 1.1, green)
addprefix("expensive", 1.8, red)
addprefix("lewd", 1.6, orange)
addprefix("greasy", 0.95, green)
addprefix("adorable", 1.2, blue)
addprefix("colossal", 1.4, blue)
addprefix("distinct", 1.8, red)
addprefix("acceptable", 1, blue)
addprefix("fabulous", 1.3, purple)
addprefix("resonant", 1.3, blue)
addprefix("perfect", 2.5, black)
addprefix("damaged", 0.7, light_green)
addprefix("cracked", 0.9, light_green)
addprefix("spectacular", 1.7, red)
addprefix("dusty", 1, green)
addprefix("dry", 1, green)
addprefix("incredible", 1.75, red)
addprefix("hot", 1, blue)
addprefix("basic", 1, green)
addprefix("psychotic", 0.9, light_green)
addprefix("hissing", 0.9, green)
addprefix("gay", 1, light_green)
addprefix("omniscient", 1.8, red)
addprefix("organic", 1, green)
addprefix("nutritious", 1.6, orange)
addprefix("magical", 1.9, black)
addprefix("beautiful", 1.6, orange)
addprefix("comfortable", 1, green)
addprefix("nutty", 0.9, green)
addprefix("cold", 1, green)
addprefix("illegal", 1.8, red)
addprefix("exotic", 2.1, black)
addprefix("screeching", 0.8, light_green)
addprefix("nauseating", 0.9, light_green)
addprefix("burly", 1.7, orange)
addprefix("funny", 1.2, blue)

addprefix("flaming", 1.2, orange)
addprefix("Aspect's Own", 4, black)
addprefix("monochromatic", 1.2, green)
addprefix("coincedental", 1.2, green)
addprefix("stupid", 0.3, light_green)
addprefix("ridiculous", 2.2, red)
addprefix("adjective", 1.5, orange)
addprefix("Anime", 1, green)
addprefix("slow", 0.6, light_green)
addprefix("random", 3, black)

function applyprefixestouserinventory() {
	for (var i = 0; i < user.inventory.length; i++) {
		if (user.inventory[i].prefix != false) {
			if(user.inventory[i].cube.price == trueallcubes[user.inventory[i].cube.cubeid].price && user.inventory[i].cube.name == trueallcubes[user.inventory[i].cube.cubeid].name) {
				user.inventory[i].cube.price = Math.floor((user.inventory[i].cube.price*user.inventory[i].prefix.bonus)*100)/100
				user.inventory[i].cube.name = user.inventory[i].prefix.namespace+" "+user.inventory[i].cube.name
			}
		}
	}
}
